# Generated by Django 2.2.6 on 2019-10-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('roomType', models.CharField(max_length=100)),
                ('breakfast', models.BooleanField(default=True)),
                ('transport', models.BooleanField(default=True)),
                ('numOfGuests', models.IntegerField()),
                ('checkInDate', models.DateTimeField()),
                ('checkOutDate', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='destinations.Destination')),
            ],
        ),
    ]
