# Generated by Django 2.2.6 on 2019-11-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_destination'),
        ('packages', '0004_auto_20191118_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='email',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='number',
        ),
        migrations.RemoveField(
            model_name='package',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='package',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.Hotel'),
        ),
    ]
