# Generated by Django 2.2.6 on 2019-11-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_package_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='email',
        ),
        migrations.RemoveField(
            model_name='package',
            name='number',
        ),
    ]
