# Generated by Django 2.2.6 on 2019-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_auto_20191119_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='numberOfGuests',
            field=models.CharField(max_length=10),
        ),
    ]
