# Generated by Django 2.2.6 on 2019-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_auto_20191119_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='checkInDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='checkOutDate',
            field=models.DateField(),
        ),
    ]
