# Generated by Django 2.2.6 on 2019-11-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_auto_20191119_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='breakfast',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='transport',
            field=models.CharField(max_length=100),
        ),
    ]
