# Generated by Django 2.2.6 on 2019-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_auto_20191120_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
    ]
