# Generated by Django 2.2.6 on 2019-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_auto_20191120_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='hotel',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
