# Generated by Django 2.2.6 on 2019-11-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_auto_20191120_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='checkInDate',
            new_name='checkIn',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='checkOutDate',
            new_name='checkOut',
        ),
    ]
