# Generated by Django 2.2.6 on 2019-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_auto_20191120_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='checkIn',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='checkOut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
