# Generated by Django 2.2.6 on 2019-11-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_auto_20191120_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='destination_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
