# Generated by Django 2.2.6 on 2019-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0025_package_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cost',
            field=models.FloatField(default=700.99),
            preserve_default=False,
        ),
    ]
