# Generated by Django 2.2.6 on 2019-11-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ref_code',
            field=models.CharField(default='22', max_length=20),
            preserve_default=False,
        ),
    ]
