# Generated by Django 2.2.6 on 2019-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.FloatField(default=323),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='items',
            field=models.ManyToManyField(to='packages.Package'),
        ),
        migrations.DeleteModel(
            name='BookingItem',
        ),
    ]
