# Generated by Django 2.2.6 on 2019-12-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.CharField(default='a@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
