# Generated by Django 2.2.6 on 2019-12-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_email',
        ),
    ]
