# Generated by Django 2.2.6 on 2019-11-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20191130_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='items',
        ),
        migrations.AddField(
            model_name='booking',
            name='items',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
    ]
