# Generated by Django 2.2.6 on 2019-11-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.FloatField(default=899.99),
            preserve_default=False,
        ),
    ]
