# Generated by Django 2.2.6 on 2019-11-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20191130_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='owner',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
