# Generated by Django 2.2.6 on 2019-12-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.CharField(default='a@a.com', max_length=200),
            preserve_default=False,
        ),
    ]
