# Generated by Django 2.2.6 on 2019-12-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkIn',
            field=models.DateField(default='2019-03-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='checkOut',
            field=models.DateField(default='2019-03-03'),
            preserve_default=False,
        ),
    ]
