# Generated by Django 2.2.6 on 2019-11-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20191130_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='items',
            new_name='destination',
        ),
    ]
