# Generated by Django 2.2.6 on 2019-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20191130_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
