# Generated by Django 2.2.6 on 2019-12-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20191205_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
