# Generated by Django 2.2.6 on 2019-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20191130_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination_id',
            field=models.CharField(max_length=200),
        ),
    ]
