# Generated by Django 2.2.6 on 2019-11-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20191130_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination_id',
            field=models.IntegerField(),
        ),
    ]
