# Generated by Django 2.2.6 on 2019-12-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20191130_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ref_code',
            field=models.CharField(max_length=15),
        ),
    ]
