# Generated by Django 2.2.6 on 2019-12-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20191203_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ref_code',
            field=models.CharField(max_length=200),
        ),
    ]
