# Generated by Django 2.2.6 on 2019-12-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0026_package_cost'),
        ('bookings', '0012_auto_20191203_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ManyToManyField(to='packages.Package'),
        ),
    ]
