# Generated by Django 2.2.6 on 2019-12-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0026_package_cost'),
        ('bookings', '0015_auto_20191203_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='packages.Package'),
        ),
    ]
